language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: bwEAE/E8kNW0dqscfrdByGkvpGXJkKbi4nOa+lS07MKQXFGGLs9BRER4TMz8dAZT7cDv8dh0lrzsOLSMfON4BuLX5KNwMIkdn5oN+FAeB3yEloinITh8iYxeYIuBZ7t5ZV/RS3J5UIamoJabJAQL3HI9tJSwwtDHQD7A6dEhVfuMlnVBaAkveZQzxeS7giZdXbd8zfu9kaWiXQq8u7vFGtUzZ3lzs97TjWFmdTKARv0U4tok6CnoD7wtnc5R7mg1JRlACKHtyQzcW5FR8Njo4GZDxMTFyS2tbptm8rq69d+jLalfG99ItBdLhROMXMbqsuhx8So7NsDwEvsFm7Oy9tfiFb2X/SX8DdmNNO/Kgy/VjRe65u2hSuzl5grZS+Atz0Ln8ZJvdUPXZKwG0Wq8eZTdO+PHLuUPjxUgvEKWIMJV38NR1ddgyzbLxPlzGYeNjjWMg0s00yL7HxB0eFpRJ2IWxeCNAR9Z4s0r0vzEtQB0fLsK+nc4aIfF+NOsIqp7PwRbGlSde0IINA8VmUAMNo2MgwY9GcJS1ThOmI+WVLXoyQFpozK8vo0Eh16XzwT8yoqBvRFY6lK2nviMZ629W9jAX2c99nOuQXrEZhEzLin8sTCOqjgMhYBl1BQDnodZxuyyEzIvUhRsnw9VgjCLI83OggbG5G2raj7weuUjWo8=
  app: dinowarranty
  run:
    - "npm run build"
    - "npm run dev"
notifications:
  email:
    on_success: always
    on_failure: always