language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: W9yFWJv+nxoBtp2L8leos9d/4Rvk6AaNvqo7VRpJiBl8rFLuPnJ48yn0tpjpWJ1iEuOFj5S4SuH5k+EZlGQLJYUxblkC8EKax0gnYear+NGCXODO5ffRxIIneHz6u5Bz4K6TVa4LBMZSRcBQNG+P1Zsj+dpnp9ocVAKAMl1+o3m/ijVs3DH8Ocn1W+kBuMRqHq9dIq5F7IjF0lEhCZ+ksC989SmC3cWDHgArdm4P1ELsRzOy+wghcT0Dbw6g/RFqkvVrzP4dw2rPU4sxVqrlActNwE+4ToFrUspRJLJDBXle0EoA3GVOhVOlY2YmnFxEbccRQgz+6I1RT1fMz4DsuOciBK5PQeHAeJI1Th8jEBRK4Axk0DjsoKanUXHxP5qItkD75G/vLfVSpB05sdHix8+olC0JCft7spIBZ+8NcUffcjcyPBlYG4KxRnCHuQZqoGapyEwwFoeeCFM8GVzzadk+JZZLAHx22QagH79Ijzd4nTplzSUek3krSMc3TC8xm4BC53XFVgwSS2J3CefKaDXWsJ+LnPxploRDHi+OJZR4FZPPgbMkBw5yApJUGW4kCZ5on59tvfXy0hVHU1jkWBOrYgpOnc0LC8QHx0u9YpF7rljw05vnrf/Q20lRrPBb/nqR6IRuSUm2r/CrwRtFnEanExeNrVhe+6bdbWWkZz4=
