language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: p+ZWhbN0HwAgYfIeQpSqGeQDr2EPPXjACxu/rJF5sZgft9iOa2V6WcHJMu8B4AqcMBLIkTTRKM7eCh1qpF26tCy+eSChHxwP07sm5RGnpZK57gTWVRImnxbtSz8n4BAT58dlkvok5q4XnP70t62N9wxuiaO0aDgWKncRkt6LnYDvq8CxfKw8XCZWG8JCs2x0UG1Xkwly3WvFBG0f5nWwSuVE5zs941c8kaz+NsOj4/ARQrKJEqGHshHj60CA+IxhE4isWDY7r7w+KBHe8Hwt7UkiBDrRXsX0tXGaU/IFu/v7SxHFJ9bn1YVngWhEN5YqbzAnfScPkjBphYZAWqUZWmWQAcFW6QUjOJC7HHR3+URkQ+zQS3/Bo6F58FHdkKsJzfacpv9uKbKuASHo9AYMT8uKCYCLDRB1wLJvxay8/XFzGtWI2R3yDmQEjSfdHMdUqVYpHR5QRB3S1wI0EHJ5a9mBHVNEQ+ezdndiAAUWRExgMsKJIWTUBz+h4IpOmz9qpkVijk6CvPX6MeXGrl+vP/k2h1iXzqIy3NbFDwX4graIiSTzN62Nv9w8rXpQkjn29s+6rY91ku8ufXlgAUOAviNikc4n44Gh5t1qlaOw5AXZc0dcf0iiY6p6w0jfvsZGwsZYYTZJqsN4xbfUWkRgRV8JH4c96Ya6V8UK6fYuRGs=
  app: dinowarranty
  on:
    repo: pkovanen/dinoapp
notifications:
  email:
    on_success: always
    on_failure: always
